# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/wingtech/wt88047/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/wingtech/wt88047/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/wingtech/wt88047/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/wingtech/wt88047/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/wingtech/wt88047/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/wingtech/wt88047/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/wingtech/wt88047/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/wingtech/wt88047/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/wingtech/wt88047/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/wingtech/wt88047/proprietary/bin/vm_bms:system/bin/vm_bms \
    vendor/wingtech/wt88047/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/wingtech/wt88047/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/wingtech/wt88047/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/wingtech/wt88047/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/wingtech/wt88047/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/wingtech/wt88047/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/wingtech/wt88047/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/wingtech/wt88047/proprietary/bin/cnd:system/bin/cnd \
    vendor/wingtech/wt88047/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
    vendor/wingtech/wt88047/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
    vendor/wingtech/wt88047/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/wingtech/wt88047/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmasc.so:system/vendor/lib/libmasc.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/wingtech/wt88047/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/wingtech/wt88047/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/wingtech/wt88047/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
    vendor/wingtech/wt88047/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    vendor/wingtech/wt88047/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/wingtech/wt88047/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/wingtech/wt88047/proprietary/bin/location-mq:system/bin/location-mq \
    vendor/wingtech/wt88047/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/wingtech/wt88047/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/wingtech/wt88047/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/wingtech/wt88047/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/wingtech/wt88047/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
    vendor/wingtech/wt88047/proprietary/bin/perfd:system/bin/perfd \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/wingtech/wt88047/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/wingtech/wt88047/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/wingtech/wt88047/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/wingtech/wt88047/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/wingtech/wt88047/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/wingtech/wt88047/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/wingtech/wt88047/proprietary/bin/radish:system/bin/radish \
    vendor/wingtech/wt88047/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/wingtech/wt88047/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/wingtech/wt88047/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/wingtech/wt88047/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/wingtech/wt88047/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/wingtech/wt88047/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/wingtech/wt88047/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/wingtech/wt88047/proprietary/lib/libwcnss_qmi.so:system/lib/libwcnss_qmi.so

PRODUCT_COPY_FILES += \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libactuator_dw9714_ov5648_rendang.so:system/vendor/lib/libactuator_dw9714_ov5648_rendang.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libactuator_dw9714_ov5648_rendang_camcorder.so:system/vendor/lib/libactuator_dw9714_ov5648_rendang_camcorder.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libactuator_dw9714_ov5648_rendang_camera.so:system/vendor/lib/libactuator_dw9714_ov5648_rendang_camera.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libactuator_dw9714_ov5670_rendang.so:system/vendor/lib/libactuator_dw9714_ov5670_rendang.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libactuator_dw9714_ov5670_rendang_camcorder.so:system/vendor/lib/libactuator_dw9714_ov5670_rendang_camcorder.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libactuator_dw9714_ov5670_rendang_camera.so:system/vendor/lib/libactuator_dw9714_ov5670_rendang_camera.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_gc2355_rendang_common.so:system/vendor/lib/libchromatix_gc2355_rendang_common.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_gc2355_rendang_preview.so:system/vendor/lib/libchromatix_gc2355_rendang_preview.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_rendang_common.so:system/vendor/lib/libchromatix_ov5648_q5v22e_rendang_common.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_rendang_default_video_hd.so:system/vendor/lib/libchromatix_ov5648_q5v22e_rendang_default_video_hd.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_rendang_default_video.so:system/vendor/lib/libchromatix_ov5648_q5v22e_rendang_default_video.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_rendang_preview.so:system/vendor/lib/libchromatix_ov5648_q5v22e_rendang_preview.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_rendang_snapshot.so:system/vendor/lib/libchromatix_ov5648_q5v22e_rendang_snapshot.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5648_q5v22e_rendang_zsl.so:system/vendor/lib/libchromatix_ov5648_q5v22e_rendang_zsl.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_common.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_common.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_default_video.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_default_video.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_hfr_120fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_hfr_120fps.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_hfr_60fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_hfr_60fps.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_hfr_90fps.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_hfr_90fps.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_liveshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_liveshot.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_preview.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_preview.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_snapshot.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_snapshot.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_video_hd.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_video_hd.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_rendang_zsl.so:system/vendor/lib/libchromatix_ov5670_q5v41b_rendang_zsl.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_gc2355_rendang.so:system/vendor/lib/libmmcamera_gc2355_rendang.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_ov5648_q5v22e_rendang.so:system/vendor/lib/libmmcamera_ov5648_q5v22e_rendang.so \
    vendor/wingtech/wt88047/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b.so:system/vendor/lib/libmmcamera_ov5670_q5v41b.so
endif
